/**
 * Bingó cellák: a 2025–2026-os választási időszakban a kormányzati és kormányközeli
 * kommunikációban, plakátokon és médiában ismétlődő Tisza- / ellenzék-ellenes narratívák
 * rövid összefoglalói (szatirikus bingóhoz – nem idézetek).
 */
export const DEFAULT_BINGO_TEXTS: readonly string[] = [
  "Ezer forintos benzin literje",
  "Megszűnik a rezsicsökkentés",
  "Belevinnének minket az ukrán háborúba",
  "A Tisza eltörölné a védett üzemanyagárat",
  "Leválasztanák Magyarországot az olcsó orosz energiáról",
  "A rezsi háromszorosára nőne",
  "Brüsszel energiapolitikájára kényszerítenének",
  "Az orosz energia azonnali kivezetése",
  "Energiafüggetlenségi adó",
  "MVM privatizáció / eladása",
  "MOL-részvények eladása",
  "Az egekbe lőnének az energiaárakat",
  "A Tisza pártot az ukránok pénzelik",
  "Ukránpárti kormányt akarnak",
  "Fegyvert, pénzt, katonát adnának Ukrajnának",
  "Európai katonák az ukrán frontra – mi is belecsúsznánk",
  "„Győzelmi terv” Ukrajnának",
  "Ukrajna NATO-tagságának támogatása",
  "Sorkötelezettség visszaállítása",
  "Magyar katonák a frontra, ha Brüsszel kéri",
  "Brüsszel diktál a befagyasztott pénzekért cserébe",
  "A Tisza Brüsszelt szolgálná, nem Magyarországot",
  "EPP / Manfred Weber vonal – háborúpárti szövetség",
  "Brüsszeli milliók, hatalmas EP-fizetés",
  "Tisza-adó mindenkire",
  "Bruttó 400 ezer felett több adót fizetnének",
  "Keresetcsökkenés minden munkavállalónak",
  "QR-kódos „Tisza-adó” plakátok",
  "A családi adókedvezményt elvennék",
  "A gyerekek utáni kedvezményeket visszavágnák",
  "Kötelező migránskvóta elfogadása",
  "Migránsok tömeges betelepítése",
  "Brüsszel migrációs szabályai helyett magyar döntés megszűnne",
  "Gender-propaganda az iskolákban",
  "A „genderőrület” terjesztése",
  "Nemzeti stratégiai vagyont eladnák",
  "Az orosz energiát „kidobnák” – drágul minden",
  "Szankciók nélküli pragmatikus politika megszűnne",
  "A béke helyett háború lenne a tét",
  "„Ha a Tisza nyer” – összeomlás jön",
  "Devizában / dollárban érkező utasítások (Brüsszelből)",
  "Soros-szál / külföldi háttér",
  "A nemzeti függetlenség feladása",
  "Rezsibotrány és rezsiár-sokk",
  "Benzinár-sokk és üzemanyag-drágulás",
  "A magyar energiaellátás kockáztatása",
  "Háborúpárti baloldal / ellenzék",
  "Ukrajna „győzelméért” kötelező szolidaritás",
  "NATO-csapatok, fegyverek, pénz – végtelen spirál",
  "A rezsit és a benzinár védelmét eltörölnék",
  "A kormány „védi a rezsit” – ők elvennék",
  "A kormány „védi a benzinárat” – ők felszámolnák",
  "Brüsszeli győzelmi terv aláírása",
  "EP-frakciócsatlakozás = háborúpárti kötelezettségek",
  "Külföldi nyomásra változtatnák a külpolitikát",
  "Az olcsó rezsi csak addig marad, amíg ők távol vannak",
  "Rezsitámogatás és ársapka eltörlése",
  "Jövedéki adó és üzemanyag-politika „brüsszeli mintára”",
  "Energiamix átírása – minden drágul",
  "Orosz olaj és gáz azonnali stop – árrobbanás",
  "Lakossági gáz és áram piaci árazás „teljes egészében”",
  "Családok büntetése adókkal",
  "Nyugdíjasok büntetése megszorításokkal",
  "„Mindenki fizessen” – új közterhek",
  "Áfacsökkentések helyett új adónemek",
  "Kórházi és egészségügyi támogatások elvonása (ellenzék-ellenes keret)",
  "Föld és agrárvagyon „eladósodása”",
  "Nemzeti bank és gazdaságpolitika Brüsszel felügyelete alatt",
  "Költségvetési fegyelem helyett eladósodás",
  "EU-s pénzekért cserébe politikai zsarolás elfogadása",
  "Magyar érdek helyett „európai érdek” – minden engedmény",
  "Külföldi NGO-k és „civil” beavatkozás megerősödése",
  "Börtön helyett „európai normák” – bűnözők kedvezményei (kampány-kép)",
  "Határőrizet felpuhítása a kvóták miatt",
  "Kötelező szolidaritási befogadás",
  "„Európai értékek” kényszerítése az oktatásban",
  "Nemzeti konzultáció helyett külföldi diktátum",
  "Szuverenitás feladása a jogállamisági zsarolással",
  "Közösségi média és „független” sajtó háborúpárti narratívája",
  "„Átláthatóság” mögött külföldi finanszírozás",
  "Választási csalás / biznisz vádak (ellenzék ellen)",
  "Hamis bizonyítékok gyártása a kormány ellen",
  "Lejárató kampány a nemzeti oldal ellen",
  "Mémek és plakátok hada a Tisza ellen",
  "Óriásplakát-háború – minden sarkon ugyanaz az üzenet",
  "„Szakértők” Brüsszelből írják a programot",
  "Külpolitikai „szakértők” – Ukrajna NATO és háború",
  "Fegyverszállítás és katonai segítség növelése",
  "Magyar fiatalok a háborúba (rémtörténet verzió)",
  "Béke helyett háborús gazdaság és sorozás",
  "Rezsicsökkentés „fenntarthatatlan” – el kell törölni (ellenzékre kenve)",
  "Üzemanyag-árstop „butaság” – piacra tennék",
  "Rezsitámogatás „fideszes mutyi” – eltörölnék (ellenzék-ellenes frame)",
  "Orosz energia = olcsóság – ez „rossz”, el kell vágni",
  "Szankciók melletti kötelező állásfoglalás",
  "Közös európai hadsereg / katonai kötelezettségek",
  "Katonai kiadások növelése háborús kötelezettséggel",
  "Transzatlanti nyomás – mindent odaadnánk",
  "Ukrajna támogatása „nem kérdés” – nálunk sem",
  "„Nem engedünk Putyinnak” – minden áron, magyar áron",
  "Energiaszankciók teljes körű végrehajtása",
  "Gáz- és olajimport leállítása – áremelkedés",
  "Lakossági rezsitámogatás fokozatos kiürítése",
  "Vállalkozók és KATA-sok újabb sarcai (ellenzék-ellenes keret)",
  "Adóemelés és új illetékek „Tisza-csomagban”",
  "Járulékok és közterhek növelése",
  "Bér utáni adók emelkedése",
  "Családi pótlék és támogatások „racionalizálása” (csökkentés)",
  "Nyugdíj és nyugdíjas támogatások „reformja”",
  "Egészségügy privatizációja / drágább ellátás",
  "Oktatás „európai mintára” – kötelező ideológiák",
  "Egyház és nemzeti identitás háttérbe szorítása",
  "Nemzeti ünnepek és hagyományok „elavultak”",
  "Határon túl magyarok „nem prioritás”",
  "Külhoni támogatások megnyirbálása",
  "Nemzeti média és közmédia felszámolása / tisztogatás",
  "Közbeszerzések és nemzeti cégek hátrányba helyezése",
  "Stratégiai ágazatokban külföldi tulajdon",
  "Víz, energia, hulladék – mind külföldi kézben",
  "Lakhatási támogatások csökkentése",
  "Albérlet- és hitelpiac drágulása adókkal",
  "Devizahiteles / banki rémület (régi minta újra)",
  "„Gyurcsány-show” folytatása (összeomlás-emlékeztető)",
  "2008 és 2010 előtti káosz visszatér",
  "IMF és Brüsszel közös programja",
  "Költségvetési megszorítások és megszorító csomag",
  "Áremelkedés mindenhol – csak a „váltó” után",
  "Forint gyengülése és dráguló import",
  "Infláció újraindítása politikai változással",
  "Rezsicsökkentés nélkül hideg lakás, melegítő nélkül",
  "Télen drága gáz – „Tisza-terv” ára",
  "Autózás luxus – ezer forintos liter",
  "Vidék elnéptelenedése energiaárak miatt",
  "Családi házak rezsiár-robbanása",
  "Napelem és klíma helyett új adók",
  "Zöld átállás kényszere drágán",
  "Szén és atom ellen – még drágább áram",
  "Import LNG és drága energia Brüsszelből",
  "Energetikai szuverenitás feladása",
  "Paksi és nemzeti energia projektek blokkolása",
  "Orosz kapcsolatok teljes felrúgása",
  "V4 és regionális szövetség feladása",
  "Külpolitikai magány – csak Brüsszel felé",
  "Ukrajnának minden, Magyarországnak semmi",
  "Határ menti háború kockázata növekszik",
  "Magyarország fegyverszállító bázis (rémtörténet)",
  "NATO-csapatmegállapodások bővítése",
  "Kötelező euró gyorsan és minden áron",
  "Euró bevezetése árfolyam- és ársokk nélkül (ellenzék-ellenes keret)",
  "Jogállamisági zsarolás elfogadása pénzért",
  "7 pont / 17 pont / brüsszeli feltételek teljesítése",
  "Migránsok elszállásolása magyar falvakban",
  "Kötelező kvóta szerinti betelepítési kötelezettség",
  "Határkerítés „embarrassing” – lebontanák (kampány-kép)",
  "Schengen és határvédelem felpuhítása",
  "Bűnözés növekedése migrációval",
  "No-go zónák és gettók (nyugati minta import)",
  "LMBTQ-aktivisták kötelező órái",
  "Nemi nevelés „európai szabvány” szerint",
  "Szülői jogok korlátozása az iskolában",
  "Egyházi iskolák hátrányba helyezése",
  "Nemzeti történelem oktatás gyengítése",
  "Nemzeti konzervatív kormányzás vége",
  "„Haladás” és „európai normák” minden áron",
  "Közösségi finanszírozás és offshore háttér (lejárató narratíva)",
  "Átláthatatlan pártfinanszírozás külföldről",
  "„Civil” szervezetek politikai kampányt finanszírodnak",
  "Külföldi sajtó és ügynökök magyar belpolitikában",
  "Lejárató anyagok gyártása választás előtt",
  "Álhírek és deepfake hadviselés",
  "Választási bizottság és intézmények „elfoglalása”",
  "Alaptörvény és nemzeti keretek gyengítése",
  "Alkotmánybíróság és bíróságok „függetlenítése” külföldi mintára",
  "Közigazgatás politikai tisztogatása",
  "Önkormányzatok centralizálása és felszámolása",
  "Főváros és vidék közötti szakítás",
  "Budapest „különálló köztársaság” (ellenzék-ellenes kép)",
  "Falusi élet drágítása és elnéptelenedés",
  "Mezőgazdaság támogatások EU-s feltételekhez kötése",
  "Magyar élelmiszer drágul export és szabályozás miatt",
  "Ukrán gabona és olcsó import – magyar gazda hátrányban (kampány-keret)",
  "Rezsitámogatás megszűnése = családok tönkremennek",
  "Benzinár felszabadítása = tömegközlekedés is drágul",
  "Minden szektorban új közterhek",
  "Digitális adó és bankadó (új sarc narratíva)",
  "Vagyon- és ingatlanadó növelése",
  "Örökösödési és tranzakciós adók",
  "Cégek elvándorlása adóemelés miatt",
  "Munkahelyek csökkenése válságban",
  "Munkanélküliség és leépítések",
  "Devizahiteles rémálom visszatér",
  "Bankok és multik nyernek, magyar családok veszítenek",
  "Külföldi tulajdon minden szektorban",
  "Nemzeti tőke és magyar KKV-k ellehetetlenítése",
  "Állami vállalatok kiárusítása",
  "Stratégiai nyersanyag és energia külföldi kézben",
  "Közművek és vízművek privatizációja",
  "Egészségügyi beszállítók és gyógyszerárak emelkedése",
  "Oltások és egészségügy brüsszeli beszerzésre kényszerítve",
  "Idősek ellátása romlik",
  "Szülészetek és kórházak bezárása takarékossággal",
  "Orvosok elvándorlása béremelés nélkül",
  "Béremelés helyette új adók",
  "Minimálbér „szép szavak”, reálérték csökkenés",
  "Szakszervezetek és érdekvédelem gyengítése",
  "Béke és stabilitás elvesztése",
  "Választás utáni „meglepetés csomag”",
  "Kampányban minden olcsó, kormányon minden drága (ellenzékre kenve)",
  "Brüsszel és Washington közös kormánya",
  "Külföldi nagykövetségek utasítanak",
  "Nemzeti ünnepen is a háború a téma",
  "Zászló és himnusz háttérbe szorul",
  "Keresztény-konzervatív értékek támadása",
  "Egyházak megadóztatása",
  "Hit és család ügyei háttérbe",
  "Gender és migráció előtérbe",
  "Nemzeti identitás „elavult”",
  "Magyarország „hibás” és „javításra szorul” Brüsszel szerint",
  "Büntetőjogi szigor helyett „emberibb” bűnözőbarát szabályok",
  "Határőrizet és kitoloncolás gyengítése",
  "Bűnözők és embercsempészek kedvezőbb helyzete",
  "Terror és biztonság kockázata nő",
  "Közterületi rend és közbiztonság romlása",
  "Rendőrség és titkosszolgálat politikai utasításra",
  "Nemzeti hírszerzés gyengítése",
  "Kiberbiztonság és energiaellátás kiszolgáltatottsága",
  "Orosz és keleti piacok elvesztése",
  "Export és magyar gazdaság zuhanása",
  "Turizmus és vendéglátás drágulás miatt összeesik",
  "Vidéki vendéglátás és fesztiválok adóval megfojtva",
  "Kisvállalkozások bezárása",
  "Helyi termelők támogatásának megvonása",
  "Nemzeti élelmiszer-stratégia feladása",
  "GMO és import dömping",
  "Földtulajdon külföldieknek engedélyezése",
  "Termőföld spekuláció és külföldi cégek",
  "Víz és természetvédelem ideológiai okokból",
  "Ipar és kohászat leépítése zöld címén",
  "Atomenergia ellen – import áram drágán",
  "Nap- és szélenergia kényszer drága tároló nélkül",
  "Rezsitámogatás nélkül téli halálesetek (kampány-hiperbola)",
  "Hideg lakások és megfázások tömege (kampány-hiperbola)",
  "Nyugdíjasok rezsijét nem fizetik – „reform”",
  "Nyugdíj reálérték csökkenése",
  "13. havi nyugdíj és kiegészítések megnyirbálása",
  "Idősek gyógyszere drágul",
  "BKK és tömegközlekedés drágulása",
  "Útdíj és parkolás mindenütt",
  "Autóhasználat büntetése adókkal",
  "Vidék közlekedése ellehetetlenül",
  "Teherautók és mezőgazdasági üzemanyag drágulása",
  "Élelmiszerárak további emelkedése energia miatt",
  "Pékáru, tej, hús mind drágább",
  "Rezsivel együtt az élelmiszer is elviselhetetlen",
  "Kamatok és hitelek drágulása",
  "Lakáshitel és építkezés leáll",
  "Fiatalok el sem tudnak költözni",
  "CSOK és családtámogatások csökkentése",
  "Gyermekvállalás anyagi támogatásának megnyirbálása",
  "Óvodai és bölcsődei férőhelyek csökkenése",
  "Iskolai étkeztetés drágulása",
  "Egyetemi tandíj és diákhitel drágulása",
  "Magyar diploma értékének csökkenése külföldi egyetemek javára",
  "Szakképzés és ipar összehangolatlansága",
  "Mérnök és orvos hiány növekedése",
  "Elvándorlás újabb hulláma",
  "Magyar fiatalok külföldre kényszerülnek",
  "Agyelszívás és nemzeti veszteség",
  "Nyugdíjrendszer összeomlása reform néven",
  "Egészségbiztosítás járulékemelés",
  "Magán-egészségügy előnybe – közellátás lepusztul",
  "Kórházi hálapénz helyett fizetős minden",
  "Várólisták növekedése",
  "Halálozás és életkilátások romlása (kampány-keret)",
  "Covid-szerű válságkezelés újra – korlátozások",
  "Digitális útlevél és korlátozások Brüsszelből",
  "Adatvédelem gyengítése uniós szabályokkal",
  "Nemzeti adatvagyon külföldi felhőben",
  "Kötelező regisztrációk és azonosítás mindenben",
  "Készpénz és anonimitás felszámolása",
  "Oltások és egészségügyi kötelezettségek bővítése",
  "Szülői döntés korlátozása gyermekügyekben",
  "Kötelező „érzékenyítő” programok",
  "Nemzeti kulturális intézmények megszorítása",
  "Múzeumok és színházak elidegenítése",
  "Nemzeti film és média támogatás megvonása",
  "Közösségi értékek helyett globális popkult",
  "Magyar zene és irodalom háttérbe",
  "Nemzeti sport és utánpótlás támogatás csökkenése",
  "Stadionok és közösségi sport helyett ideológia",
  "Határon túli focitámogatás megnyirbálása",
  "Nemzeti válogatott és identitás gyengítése",
  "Külföldi klubok és ügynökök előnyben",
  "Magyar munkaerő olcsó külföldnek",
  "Bérmunka és exportleány a multiknak",
  "Termelőüzemek leköltöznek Romániába és Szerbiába",
  "Magyar adórendszer versenyképességének vége",
  "KKV-k adminisztratív terhei növekednek",
  "Ellenőrzések és bírságok gyarapodnak",
  "NAV és hatósági nyomás politikai célzattal (ellenzék-ellenes kép)",
  "Korrupció vád minden nemzeti projektre",
  "Nemzeti beruházások leállítása",
  "Út és vasútfejlesztés leáll",
  "Vidéki infrastruktúra hanyatlik",
  "Internet és mobil drágulás új adókkal",
  "Digitális kormányzás helyett digitális megfigyelés",
  "Nemzeti cloud és IT-stratégia feladása",
  "Kibervédelem külföldi cégekre bízva",
  "Kritikus infrastruktúra kiszolgáltatottsága",
  "Vízellátás és árvízvédelem forrásainak elvonása",
  "Mezőgazdasági víz és öntözés drágulása",
  "Aszály és termés kár – támogatás nélkül",
  "Élelmiszer-biztonság gyengülése",
  "Importfüggőség növekedése",
  "Stratégiai tartalékok felélése",
  "Katonai és polgári védelem gyengítése",
  "Honvédség leépítése és beolvasztása NATO-kötelezettségbe",
  "Kötelező szolgálat vissza – háborúhoz közelítve",
  "Tartalékosok behívása és mozgósítás",
  "Lőszerek és fegyverek gyártása külföldnek",
  "Magyar gyárak háborús termelésre állnak át",
  "Légter és repterek NATO-katonák előtti megnyitása",
  "Határ menti övezetek katonai zónává válása",
  "Menekültek és háborús hullámok Magyarországon",
  "Biztonsági kockázat és terrorveszély növekedése",
  "Schengen belső határellenőrzések visszatérése",
  "Gazdasági válság és munkanélküliség spirál",
  "Forintosítás és devizahitelek káosza",
  "Bankrendszer instabilitása",
  "Államcsőd és IMF (rémtörténet verzió)",
  "Költségvetési hiány és megszorító csomag",
  "Növekedés helyett recesszió és zuhanás",
  "Beruházások leállása külföldi bizonytalanság miatt",
  "Magyarország leminősítése és drága hitelek",
  "Államadósság spirál",
  "Jólét és rezsicsökkentés korszakának vége",
  "„Boldog békeidő” helyett háború és drágulás",
  "Választás után minden ígéret elfelejtve",
  "Kampányban béke, kormányon háború (ellenzékre kenve)",
  "Brüsszeli és ukrán érdek minden magyar elé",
  "Magyar családok utolsók a sorban",
  "Nemzeti érdek nélküli kormányzás",
  "Szuverenitás és rezsivédelem egy nap alatt elveszne",
];
